AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Flying Js serverless wedding RSVP application.

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket that contains the zipped wedding code.
    Default: flyingj-code-dev
  CodeKey:
    Type: String
    Description: S3 object key of the zipped wedding code.

Resources:
  Parties:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.parties_handler
      Runtime: python3.6
      Policies:
        - Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Resource: !GetAtt
              - PartiesTable
              - Arn
            Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:DeleteItem
              - dynamodb:Scan
              - dynamodb:Query
              - dynamodb:UpdateItem
              - dynamodb:CreateTable
              - dynamodb:DescribeTable
              - dynamodb:GetShardIterator
              - dynamodb:GetItem
              - dynamodb:UpdateTable
              - dynamodb:GetRecords
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref CodeKey
      Environment:
        Variables:
          PARTIES_TABLE: !Ref PartiesTable
      Events:
        GetParties:
          Type: Api
          Properties:
            Path: /parties
            Method: get
        GetParty:
          Type: Api
          Properties:
            Path: /parties/{id}
            Method: get
        UpdateParty:
          Type: Api
          Properties:
            Path: /parties/{id}
            Method: post
        CreateParty:
          Type: Api
          Properties:
            Path: /parties
            Method: post
        DeleteParty:
          Type: Api
          Properties:
            Path: /parties/{id}
            Method: delete
  PartiesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
